04 exercice from day 01

**The sbuject**:

The goal of this exercice is to learn to generate random data.
In Data Science it is extremely useful to generate random data for many reasons: 
Lack of real data, create a random benchmark, use varied data sets. 
NumPy proposes a lot of options to generate random data. In statistics, assumptions are made on the distribution the data is from. All data distribution that can be generated randomly are described in the documentation. In this exerice we will focus on two distributions:

- Uniform: For example, if your goal is to generate a random number from 1 to 100 and that the probability that all the numbers is equal you'll need the uniform distribution. NumPy provides `randint` and `uniform` to generate uniform distribution
- Normal: The normal distribution is the most important probability distribution in statistics because it fits many natural phenomena.For example, if you need to generate a data sample that represents **Heights of 14 Year Old Girls** it can be done using the normal distribution. In that case, we need two parameters: the mean (1m51) and the standard deviation (0.0741m). NumPy provides `randn` to generate normal distribution (among other)
https://docs.scipy.org/doc/NumPy-1.15.0/reference/routines.random.html

1. Set the seed to 888
2. Generate a **one-dimensional**  array of size 100 with a normal distribution 
3. Generate a **two-dimensional** array of size 8,8 with random integers from 1 to 10 - both included (same probability for each integer)
4. Generate a **three-dimensional** of size 4,2,5 array with random integers from 1 to 17 - both included (same probability for each integer)


In [30]:
import numpy as np

# https://numpy.org/doc/1.16/reference/generated/numpy.random.randint.html#numpy.random.randint

rnd_seed = np.random.seed(888)

print(rnd_seed)

# uniform distribution
# one_dimen = np.random.rand(100)

# normal distribution
one_dimen = np.random.randn(100)

# print(one_dimen)

# same probability for each integer
two_dimen = np.random.randint(1, 11, size=(8,8))

# print(two_dimen)

# same probability for each integer
three_dimen = np.random.randint(1, 18, size=(4, 2, 5))

# print(three_dimen)


None
[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]
